schema:
  format:
    openapi: "3.0.0"
  environment_input_type: "ApprunnerServiceInput"
  types:
    ApprunnerServiceInput:
      type: object
      description: "Input properties for my environment"
      properties:
        http_port:
          title: "Port"
          type: number
          description: "The port to route traffic to"
          default: 80
          minimum: 0
          maximum: 65535
        apprunner_name:
          title: "Apprunner name"
          type: string
          description: "The Apprunner name"
          default: "proton-test"
          minLength: 1
          maxLength: 200
