schema:
  format:
    openapi: "3.0.0"
  environment_input_type: "AppRunnerEnvironmentInput"
  types:
    AppRunnerEnvironmentInput:
      type: object
      description: "Input properties for my environment"
      properties:
        http_port:
          type: number
          description: "The HTTP port to run the app"
          default: 8000
          pattern: ^((6553[0-5])|(655[0-2][0-9])|(65[0-4][0-9]{2})|(6[0-4][0-9]{3})|([1-5][0-9]{4})|([0-5]{0,5})|([0-9]{1,4}))$
        app_runner_name:
          type: string
          description: "The HTTP port to run the app"
          default: proton-test
